# Railway PostgreSQL Kal?c? Veritaban? Ayarlar?
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=lCTTXdcWODzZHegeIfcKNruAmLLByoNR
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# YEN? EKLENEN: Oturumlar? (Giri?leri) RAM yerine Veritaban?nda Kal?c? Tutma Ayar?
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always