# Railway PostgreSQL Database Settings
# Password is provided via Railway Variables

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://centerbeam.proxy.rlwy.net:31505/railway}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Database Session Management Settings
# Spring Session Veritaban\u0131 Ayarlar\u0131
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always